language: node_js
install:
  - npm install --ignore-scripts
before_script:
  - git submodule update --init
  - npm install -g codeclimate-test-reporter
jobs:
  include:
    - node_js: 10
      script:
        - npm run build
        - npm run test-cov
    - node_js: 12
      script:
        - npm run build
        - npm run test-spec
    - node_js: 14
      script:
        - npm run build
        - npm run test-spec
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - coveralls < coverage/lcov.info
  - scripts/travis-gh-pages
  - scripts/publish-built-version
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9cab5fe0c9595511cd81
    on_success: change
    on_failure: always
    on_start: never
